AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resume

  Sample SAM Template for resume

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetPageCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_page_count/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get_page_count
            Method: GET

  UpdatePageCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_page_count/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /update_page_count
            Method: GET

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: visitor-counter
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
      
      BillingMode: PAY_PER_REQUEST
      

